// export const INCREMENT = 'INCREMENT'
export const SAVE_VALUES = 'SAVE_VALUES'
export const UPDATE_VALUES = 'UPDATE_VALUES'
export const DELETE_VALUE = 'DELETE_VALUE'
export const EDIT_VALUE = 'EDIT_VALUE'
export const NO_EDIT = 'NO_EDIT'